# Generated by Django 3.2.18 on 2023-06-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WashroomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.TextField()),
                ('date_updated', models.TextField()),
                ('_id', models.TextField()),
                ('parent_id', models.TextField()),
                ('asset_id', models.TextField()),
                ('alternative_name', models.TextField()),
                ('washroom_type', models.TextField()),
                ('accessible', models.TextField()),
                ('hours', models.TextField()),
                ('location_details', models.TextField()),
                ('url', models.TextField()),
                ('address', models.TextField()),
                ('geometry', models.TextField()),
            ],
        ),
    ]
