# Generated by Django 3.2.18 on 2023-06-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicmap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='washroomdata',
            old_name='_id',
            new_name='opendata_id',
        ),
    ]
