# Generated by Django 3.2.18 on 2023-07-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicmap', '0002_rename__id_washroomdata_opendata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washroomdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='washroomdata',
            name='opendata_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
